### ISSUE TITLE
motivatie.me

### ISSUE THREAD

**Issue by ghost** [RobLui/web-backend-oplossingen#1]
Robbert, geniepige valsspeler :) Je hebt de tekst van Jens overgenomen zonder je eigen tekst te schrijven. Het draait om meer dan alleen dat groene vinkje hé :)

**Comment by RobLui** [comment]
Dag Pascal,

Ik ben het wel niet zo te weten gekomen hoor ;)
Ik ben effectief op de errors gaan inspecteren :) die via -GET- werd veroorzaakt,
Toen had ik door dat het van myn github werd gepulled, en ben ik gaan controleren bij Jens of het effectief zo was :)
Ik heb de text die Jens had staan inderdaad overgenomen, en dat is alles :)

Greetz,
Robbert

Op 28 okt. 2016 om 14:04 heeft Pascal Nosenzo <notifications@github.com<mailto:notifications@github.com>> het volgende geschreven:

Robbert, geniepige valsspeler :) Je hebt de tekst van Jens overgenomen zonder je eigen tekst te schrijven. Het draait om meer dan alleen dat groene vinkje h? :)

##

**Comment by RobLui** [comment]
Plus!

Ik wou myn groen vinkje al hebben staan :)
Ik ging daarna myn eigen text inzenden, ik heb op dit moment wiskunde waardoor ik dat nog niet heb gedaan :)

Robbert

Op 28 okt. 2016 om 14:04 heeft Pascal Nosenzo <notifications@github.com<mailto:notifications@github.com>> het volgende geschreven:

Robbert, geniepige valsspeler :) Je hebt de tekst van Jens overgenomen zonder je eigen tekst te schrijven. Het draait om meer dan alleen dat groene vinkje h? :)

##

**Comment by RobLui** [comment]
Beste Pascal,

Markdown down & feedback from myself up :)

Kind regards,

Robbert

---

Van: Pascal Nosenzo notifications@github.com
Verzonden: vrijdag 28 oktober 2016 12:04
Aan: RobLui/web-backend-oplossingen
Onderwerp: [RobLui/web-backend-oplossingen] motivatie.me (#1)

Robbert, geniepige valsspeler :) Je hebt de tekst van Jens overgenomen zonder je eigen tekst te schrijven. Het draait om meer dan alleen dat groene vinkje hé :)

##

**Comment by ghost** [comment]
't Is ok hoor, was gewoon nieuwsgierig naar je motivatie en feedback. Merci voor de eerlijke input! ;)

**Comment by RobLui** [comment]
Ok!

Ik vond het trouwens een heel originele periodeopdracht, zo heb ik er nog geen enkele geweten!

Simpel, maar als je der niets van kent lijk het me toch niet simpel. [😊]

grtz,

Robbert

---

Van: Pascal Nosenzo notifications@github.com
Verzonden: vrijdag 28 oktober 2016 18:15
Aan: RobLui/web-backend-oplossingen
CC: Robbert; State change
Onderwerp: Re: [RobLui/web-backend-oplossingen] motivatie.me (#1)

't Is ok hoor, was gewoon nieuwsgierig naar je motivatie en feedback. Merci voor de eerlijke input! ;)
